dist: trusty
language: rust
services: docker
sudo: required

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    - env: TARGET=x86_64-unknown-linux-musl
      rust: nightly
    - env: TARGET=armv7-unknown-linux-gnueabihf
      rust: nightly
    - env: TARGET=armv7-unknown-linux-musleabihf
      rust: nightly
    - env: TARGET=x86_64-pc-windows-gnu
      rust: nightly
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: nightly

before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  api_key:
    secure: GCfatsEOAtre3ecPlkNezFrRxUfMSjgVJ5W7um7y/2RHFZqkjy9RQF2W/n2ed4qyw9j3Zl1oeROGPcWSbcQ9eM+xXkr3gZBrYqfIpZUTzuv/5XL80stQl1KZqiuH4i8CePkgWoaB8mw3/W+43UZ5TilP0iuyNU+2Ell0YUGD04eXgY4MJRHybyYRHJUvzUeAf+yv+5jXZYfgMXdNcRt9g49Mu3u0phyySIag+f80M4OkqKe2OLVd+o6gl//p4Z7IlIdimv/ygaeHHy3o0WiCSNC5CrJOtcK7ptYjQ8yeGzMsBSfDahL1rRJK5ThXYvcX8BR7FJlHZEevHMbWgSS9AcKipq6yP+QdTfzOEN7d0V5+P9AuP/n1RvdW5Y7H5dK5cFfnFDqNmhMUaZ200VJqT+6LVFdze3ojztINb7KS5mpYrV0w3GFzMhceEQntR+tpX+AqJk9JGz7WSfL/T9k0IopKbrozrpB1FFqdUX3jxebtsGnMTZrqNB/4g4nlqRx62ufsPLsTzpPoHMIe7rCCzfNV3F0wN/sBLC/Rzq3pIkMhcqSGleqaLjyckF9rC4kx0DSpOHYXAkkCsF848Y534JCE5VdgDg6oafmT4QaQ75nA3Swg+TROeS3r8idtDSBgr9JR7Bc0ETCGK7m//g/LYBWh+SlELAyaO6d7wvDNgWU=
  file_glob: true
  file: stuxsonos-$TRAVIS_TAG-$TARGET.*
  on:
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo
