dist: trusty
language: rust
services: docker
sudo: required

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    - env: TARGET=x86_64-unknown-linux-musl
      rust: nightly
    - env: TARGET=armv7-unknown-linux-gnueabihf
      rust: nightly
    - env: TARGET=armv7-unknown-linux-musleabihf
      rust: nightly
    - env: TARGET=x86_64-pc-windows-gnu
      rust: nightly
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: nightly

before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  api_key:
    secure: d/hXYW3S/ExB88DkMd4Q7Q/P3UieJjKkCzx9AP8uBVFxPVw10pizdhA69fwGDvkneG0eIgKSJ2Y+lHF2g0DaqNqWW5ycKsSyOQihOHLDGm9iK9CLQ0nNoQXe88ptLnT6COU/rd5xXy8SUE9/WvIOtwfiP9b6cjn+jbtvpzzuX8pM+A0hnzWZe4UI/ruRO78+SXaKcriC2toBi9IuGVCZJ7p8YdONDq+dnAxEoRRwf2Q22tBi3sPcWziYD/5Wal9QDr2JTdJ61jGYP2LVnrnRir4//3jq7yUPidpRhfyaej17eLZaPyrflSQiUsj81cSaixmoGeiDgW0yx5yxdm2qbGw3dp+tBZ2LUGA1McAF2MLKxl6v2pH2In8tzFc8yHAyNS38/6c/e6cis74dT32hQiYvGw/HLna4rN4elSst7kf7oUvP36q1+bJLUNIYAcNQey0FjBuISB3DLGQ5hjvb8Oxt0slMha2b5z+bTDfbvCrxGKNXmy0R+53vgU/pjtP7yF/yfTYi0UYiuuU7V9ADoywKxc4Tx/f8o764arfw7KTaoRxAruR1p5VF3jQ5JLbxLTkNgXRgLKoeoORadkFWXpiEVttn9YOCDXTvCGKp4oB0ulJQ0w91ap+Q8IE5vAB9ihw58KEQRz3lc4XcC+4XuJCaCY2R9tl7cV1usLq97sM=
  file_glob: true
  file: stuxsonos-$TRAVIS_TAG-$TARGET.*
  on:
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo
