dist: trusty
language: rust
services: docker
sudo: required

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: nightly

before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  api_key:
    secure: JIxJZG1I7a3P2kRPnm80SGSkRjsu5+gdKQegkBU7bQrigs+3Urj3IB9+/YAIGZ1MU/DiBhySjrNNOKNmVtXJkqrSsmvZvV2rD881rEmMLKQFsk0zUYHge+Pusun3LGDF3Bl9RmLm2F0FrwHA+UomoCb2rCVXBwCExkJY1FcISQBXEPkMUMbR/AZBmt57TifE7pj7veYG4p4WZyVKMfbOBruIFQspltpwROzz0pTKMZj3LUGxzZM2/FEvsMS67azbnks3CG3i26q4aKa7U2RvykgneO1/f9HP/gjv7wa69f1HJwEZL5VIPvZGMY2hXKP3m4u6e0ritIbdlBU1cranXPBUC+PMcZlBPgBK2sbmDffW/Ic+Z32QDuhmCz+xTeSedlEXpKXYyRGokvmdFEWfQJNuJGSS1wiq8Ir6PluR7MptlG5t+2NbXXzCDN9P0r8srywQDtdJPcXO3CsJtCoJYbi718e3iKsjTKV1fAtic3QEITQJwq8mgsxKav+SfO+gyEqwcKHwohbl1OpB25ZebdlB8PLyk/4NxT/51aIszgeXYMoE0HOBCOKHvyMQ7D7kEyf0cCbrCBvBGXDkH+WVbLPdesM+u6qBFHG5t6hqFASuH34aeDjbD7TkO4kg04vWZSxRBAxGGMk6KyTNyQYWwY6SjKhvLlD4ZBbbq/2UG14=
  file_glob: true
  file: stuxsonos-$TRAVIS_TAG-$TARGET.*
  on:
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - /^v\d+\.\d+\.\d+.*$/
    - master
