dist: trusty
language: rust
services: docker
sudo: required

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    - env: armv7-unknown-linux-gnueabihf
      rust: nightly
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: nightly

before_install:
  - set -e
  - rustup self update

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  api_key:
    secure: sIGx107PIN1LgzqMcQJ2zEjn88fy/mTyUJsCpPaVJ+0FcCySyOC60zdxReGIDfmPiANPLEHWSUBDgJV+FkwrKnw9hLLvXZ6cqMMGFQjE904J7GF72A3OEtgLjPUrdUd5rtavYhHSqQYe2xsCSIve8vAPC75AS1AD+jLVqYK9umJkdrnBK9ox1IwsiHbbMNGS/TSJXUgx+72hOWlst3NEnVbfs5U9obdTvMN/S5Ts47phVDnXKWVW27Iin/pzC9vO25VdEUWKFIQRGOUSL/NWgjPUeEN919NCCvxK1AmIHhy+12Ol1JAglUijqqoR+jCs1ieSyBqVGWAhbo1gctf35S9fCujih8smHNSV27YgJpD5grl7+PQXBdpOoMFUkTKpmE3696weWrZlJ8tMtlo1clYPDuIgAVfIpk4O5NGKWFE6O1SMgWbTRC5wYd5/D1E9oerSk5kjw1NS62CrKGgT0L0zZzBWatmLxTauKsFJgnA5XMFfyZPINkD2yIAVyxc6n9Q6ZpzEzd1h3HGVnpCmOPmwwN0UrDR6rt31PHguAHGfSdKs8Acygp7ibxwAXYVW4gtYTJnBUi7n+tTVbtn4RiD4MdScdhc/OxUN8Z1ilORNHQX/bXy9ZY7izTs0X7nc7Betw4e/fawUcmdDI8zMtje8XbrcGstBoZhDi+0VfqQ=
  file_glob: true
  file: stuxsonos-$TRAVIS_TAG-$TARGET.*
  on:
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo
